---
title: "Session 13"
date: "4 Feb, 2026"
output: html_notebook
---
## Create Box Plot and Violin Plot from infectivity data
```{r}
plot_df$SERINC5_group <- cut(
  plot_df$SERINC5_RPM,
  breaks = c(-Inf, 5, 20, Inf),
  labels = c("Low (0–5)", "Medium (5–20)", "High (>20)")
)
```


```{r}
plot_df$infect_group
```


```{r}
library(ggplot2)

p_violin <- ggplot(plot_df, aes(x = infect_group, y = SERINC5_RPM)) +
  geom_violin(
    aes(fill = infect_group),
    trim = FALSE,
    alpha = 0.8,
    color = "black"
  ) +
  scale_fill_manual(
    values = c(
      "low" = "red",
      "medium" = "green3",
      "high" = "blue"
    )
  ) +
  labs(
    x = "Nef infectivity group",
    y = "SERINC5 expression (RPM)"
  ) +
  coord_cartesian(ylim = c(0, 35)) +
  theme_classic() +
  theme(legend.position = "none")

print(p_violin)

```


```{r}
library(ggplot2)

p_violin <- ggplot(plot_df, aes(x = infect_group, y = SERINC5_RPM)) +
  geom_violin(
    aes(fill = infect_group),
    trim = FALSE,
    alpha = 0.8
  ) +
  geom_boxplot(
    width = 0.15,
    outlier.shape = NA,
    color = "black"
  ) +
  scale_fill_manual(
    values = c(
      "low" = "red",
      "medium" = "green3",
      "high" = "blue"
    )
  ) +
  labs(
    x = "Nef infectivity group",
    y = "SERINC5 expression (RPM)"
  ) +
  coord_cartesian(ylim = c(0, 500)) +
  theme_classic() +
  theme(legend.position = "none")

print(p_violin)

```
