---
title: " Class 7"
date: "19 Jan, 2026"
author: "Dhruvi Sheth 22294"
output: html_notebook
---

```{r}
mysqrt <- function(x){

}

```

```{r}
set.seed(123)   # for reproducibility

myData <- data.frame(
  Roll_No = sample(22001:22999, 10),                     # roll numbers starting with 22
  CPI = round(runif(10, min = 5, max = 10), 2),           # CPI up to 10
  Program = sample(c("BSMS", "BS", "MS", "PhD"), 10, replace = TRUE),
  Attendance = sample(60:100, 10, replace = TRUE)         # attendance percentage
)

df

```

## Subsetting of df

```{r}
myData[1,2] # Rows, Columns
```

```{r}
myData[2,3]
```

```{r}
myData[1:20, 2:3]
```

```{r}
myData[1:20,]
```

```{r}
myData[,3]
```

```{r}
myData[myData$Treatment %in% ]
```




## Input Data into R
# Go to the correct dictionary

```{r}
getwd()
# change/set the or working directory
```

```{r}
setwd()
```

```{r}
dir.exists("Desktop/Biostatistics/GapMinder")
```

```{r}
setwd("Desktop/Biostatistics/GapMinder")
```

```{r}
lifeExpetancyInYears <- read.csv("life_expectancy_years.csv", header = F)
```
```{r}
file.exists("Desktop/Biostatistics/GapMinder/life_expectancy_years.csv")
```

```{r}
life <- read.csv("Desktop/Biostatistics/GapMinder/life_expectancy_years.csv", header = F)
```

```{r}
head(life)
```

```{r}
str(life)
```

```{r}
head(life)
```

```{r}
dim(life)
```

```{r}
summary(life)
```
# using column names as it is

```{r}
life <- read.csv("Desktop/Biostatistics/GapMinder/life_expectancy_years.csv", header = F, check.names = FALSE)
```

